name: Validate Data

on:
  pull_request:
    paths:
      - 'data/*.yaml'
      - 'data/*.json'
  push:
    branches:
      - main
    paths:
      - 'data/*.yaml'
      - 'data/*.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Validate data
        run: npm run validate
        
      - name: Check for duplicates
        run: |
          echo "Checking for duplicate service IDs..."
          npm run validate